### ISSUE TITLE
Feature - Profile details

### ISSUE THREAD

**Issue by sjoyal** [melrodbos/TIY-Github#2]
- [x] Creating social detail section of the github for mobile viewport
  - [x] Create container for entire social detail section (`display: block`)
  - [x] Within container create 2 `<div>`s that will be set to `display: inline-block`; set width as percentage of parent element for responsive change to viewport
    - [x] First `<div>` includes octocat image; reference implementation has image size set to 110 x 110
    - [x] Second `<div>` to include 6 additional block level elements (use `<div>`s or `<li>`s)
      - [x] Each block level element includes content of varying font sizes, sans-serif font
      - [x] Suggestion for bottom four elements with icons: hardwire the icon into html and include `<span>` tag for the content to the right of the icon (allows for padding and spacing between content and the icon
      - [x] `href` links in bottom 2 elements, `text-decoration: none` to remove the underline on the link

![github-profile_details_planning](https://cloud.githubusercontent.com/assets/11789708/8012801/1e472ca8-0b92-11e5-8426-92b00e6f9420.png)

**Comment by melrodbos** [comment]
Pull Request #4
